#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"
export APPDIR="$HERE"
export PATH="${APPDIR}/usr/bin:${PATH}"
export LD_LIBRARY_PATH="${APPDIR}/usr/lib:${LD_LIBRARY_PATH}"
NODE_PATH="${APPDIR}/usr/bin:${NODE_PATH}"
exec "${APPDIR}/usr/bin/studio" "$@"
