name: Build and Release

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:      # Allow manual triggers

env:
  APP_VERSION: v1.5.2
  APP_NAME: Studio AppImage

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download AppImage artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: appimage.yml
          name: Studio.AppImage
          path: .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: Studio-*.AppImage
          tag_name: ${{ env.APP_VERSION }}
          name: ${{ env.APP_NAME }} ${{ env.APP_VERSION }}
          body: |
            ${{ env.APP_NAME }} ${{ env.APP_VERSION }}
            
            This is an unofficial AppImage build of [Studio by WordPress.com](https://github.com/Automattic/studio).
            
            ## Installation
            ```bash
            # 1. Download the AppImage
            # 2. Make it executable:
            chmod +x Studio-x86_64.AppImage
            # 3. Run it:
            ./Studio-x86_64.AppImage
            ```
            
            ## Requirements
            - Linux operating system
            - FUSE library
            
            ### Installing FUSE
            Debian/Ubuntu:
            ```bash
            sudo apt-get install libfuse2
            ```
            
            Fedora:
            ```bash
            sudo dnf install fuse
            ```
            
            Arch Linux:
            ```bash
            sudo pacman -S fuse2
            ```
            
            ## Disclaimer
            This is an unofficial package not affiliated with WordPress.com or Automattic Inc.
            Provided "as is" without warranty. Use at your own risk.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}