name: Build AppImage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            nodejs \
            npm \
            python3 \
            python3-pip \
            libfuse2 \
            wget \
            desktop-file-utils \
            patchelf
          
      - name: Make build script executable
        run: chmod +x build.sh
        
      - name: Run build script
        run: ./build.sh
        
      - name: Upload AppImage
        uses: actions/upload-artifact@v3
        with:
          name: Studio.AppImage
          path: Studio-*.AppImage 